
export const AnimalList = [
    {
      id: 1,
      name: "Lion",
      species: "Panthera leo",
      family: "Felidae",
      habitat: "Grasslands and Savannas",
      place_of_found: "Africa",
      diet: "Carnivore",
      description: "The lion is a large and powerful wild cat known for its majestic appearance and social behavior.",
      weight_kg: 190,
      height_cm: 120,
      image: "https://cdn.britannica.com/30/150930-120-D3D93F1E/lion-Namibia.jpg"
    },
    {
      id: 2,
      name: "Elephant",
      species: "Loxodonta africana",
      family: "Elephantidae",
      habitat: "Savannas, Grasslands, and Forests",
      place_of_found: "Africa, Asia",
      diet: "Herbivore",
      description: "The elephant is the largest land animal on Earth and is known for its intelligence and long trunk.",
      weight_kg: 6000,
      height_cm: 300,
      image: "https://i.natgeofe.com/k/e7ba8001-23ac-457f-aedb-abd5f2fdda62/moms5_4x3.png"
    },
    {
      id: 3,
      name: "Tiger",
      species: "Panthera tigris",
      family: "Felidae",
      habitat: "Forests, Grasslands, and Swamps",
      place_of_found: "Asia",
      diet: "Carnivore",
      description: "The tiger is a powerful predator with striking orange fur and black stripes.",
      weight_kg: 250,
      height_cm: 100,
      image: "https://images.unsplash.com/photo-1618142990632-1afb1bd67e7c?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dGlnZXJzfGVufDB8fDB8fHww"
    },
    {
      id: 4,
      name: "Kangaroo",
      species: "Macropus",
      family: "Macropodidae",
      habitat: "Forests, Grasslands, and Deserts",
      place_of_found: "Australia",
      diet: "Herbivore",
      description: "Kangaroos are marsupials known for their powerful hind legs and pouches.",
      weight_kg: 85,
      height_cm: 150,
      image: "https://i.natgeofe.com/k/aa4c480f-89ec-4c21-97c3-4348a9c310bf/kangaroo-joey_square.jpg"
    },
    {
      id: 5,
      name: "Gorilla",
      species: "Gorilla beringei",
      family: "Hominidae",
      habitat: "Forests and Mountains",
      place_of_found: "Africa",
      diet: "Herbivore",
      description: "Gorillas are large and powerful primates known for their intelligence and social structure.",
      weight_kg: 180,
      height_cm: 160,
      image: "https://files.worldwildlife.org/wwfcmsprod/images/Mountain_Gorilla_Silverback_WW22557/story_full_width/36fcoamev0_Mountain_Gorilla_Silverback_WW22557.jpg"
    },
    {
      id: 6,
      name: "Polar Bear",
      species: "Ursus maritimus",
      family: "Ursidae",
      habitat: "Arctic Region",
      place_of_found: "Arctic",
      diet: "Carnivore",
      description: "Polar bears are large carnivorous mammals adapted to life in the Arctic and primarily feed on seals.",
      weight_kg: 500,
      height_cm: 130,
      image: "https://bloximages.newyork1.vip.townnews.com/valpotorch.com/content/tncms/assets/v3/editorial/3/4b/34b39260-c783-11ec-9097-f3d860fdf9c7/626b82e91b1c1.image.jpg?resize=1200%2C755"
    },
    {
      id: 7,
      name: "Koala",
      species: "Phascolarctos cinereus",
      family: "Phascolarctidae",
      habitat: "Eucalyptus Forests",
      place_of_found: "Australia",
      diet: "Herbivore",
      description: "Koalas are arboreal marsupials known for their love of eucalyptus leaves.",
      weight_kg: 12,
      height_cm: 60,
      image: "https://d1jyxxz9imt9yb.cloudfront.net/medialib/1594/image/s1300x1300/DR_2020-01-18_Koroit-Victoria-AU_Bushfires-MosswoodWildlife-RescuedKoalas_1D_MelanieMahoney_094V1077_reduced.jpg"
    },
    {
      id: 8,
      name: "Giraffe",
      species: "Giraffa camelopardalis",
      family: "Giraffidae",
      habitat: "Savannas and Grasslands",
      place_of_found: "Africa",
      diet: "Herbivore",
      description: "Giraffes are the tallest land animals and have long necks and legs.",
      weight_kg: 800,
      height_cm: 550,
      image: "https://animalfactguide.com/wp-content/uploads/2024/11/giraffe4.jpg"
    },
    {
      id: 9,
      name: "Panda",
      species: "Ailuropoda melanoleuca",
      family: "Ursidae",
      habitat: "Bamboo Forests",
      place_of_found: "China",
      diet: "Herbivore",
      description: "Pandas are bears known for their distinctive black and white markings and love for bamboo.",
      weight_kg: 85,
      height_cm: 90,
      image: "https://bambooimport.com/cdn/shop/articles/pandabeer-scaled.jpg?v=1668091796"
    },
    {
      id: 10,
      name: "Cheetah",
      species: "Acinonyx jubatus",
      family: "Felidae",
      habitat: "Grasslands and Savannas",
      place_of_found: "Africa",
      diet: "Carnivore",
      description: "Cheetahs are the fastest land animals and have slender bodies built for speed.",
      weight_kg: 50,
      height_cm: 80,
      image: "https://thesudantimes.com/wp-content/uploads/2024/09/image_12760e-Cheetah.jpg"
    }
  ]